# Generated by Django 3.2.5 on 2021-07-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210716_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
